export const TOGGLE_THEME = 'TOGGLE_THEME';

export const SEARCH = 'SEARCH';

export const GET_RECIPE_DETAIL = 'GET_RECIPE_DETAIL';
export const CLEAN_RECIPE_DETAIL = 'CLEAN_RECIPE_DETAIL';

export const ADD_RECIPE = 'ADD_RECIPE';
export const ADD_BACKEND_ERRORS = 'ADD_BACKEND_ERRORS';
export const CLEAN_RECIPE_JUST_CREATED = 'CLEAN_RECIPE_JUST_CREATED';
export const CLEAN_BACKEND_ERRORS = 'CLEAN_BACKEND_ERRORS';