export const TOGGLE_THEME = 'TOGGLE_THEME';

export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
export const CLEAN_SEARCH_ERROR = 'CLEAN_SEARCH_ERROR';

export const GET_RECIPES = 'GET_RECIPES';
export const GET_DIETS = 'GET_DIETS';

export const FILTER_BY_ORIGIN_ALL = 'FILTER_BY_ORIGIN_ALL';
export const FILTER_BY_ORIGIN_API = 'FILTER_BY_ORIGIN_API';
export const FILTER_BY_ORIGIN_DB = 'FILTER_BY_ORIGIN_DB';

export const FILTER_BY_DIET_ALL = 'FILTER_BY_DIET_ALL';
export const FILTER_BY_DIET_VEGAN = 'FILTER_BY_DIET_VEGAN';
export const FILTER_BY_DIET_VEGETARIAN = 'FILTER_BY_DIET_VEGETARIAN';
export const FILTER_BY_DIET_GLUTENFREE = 'FILTER_BY_DIET_GLUTENFREE';


export const GET_RECIPE_DETAIL = 'GET_RECIPE_DETAIL';
export const CLEAN_RECIPE_DETAIL = 'CLEAN_RECIPE_DETAIL';

export const ADD_RECIPE = 'ADD_RECIPE';
export const ADD_BACKEND_ERRORS = 'ADD_BACKEND_ERRORS';
export const CLEAN_RECIPE_JUST_CREATED = 'CLEAN_RECIPE_JUST_CREATED';
export const CLEAN_BACKEND_ERRORS = 'CLEAN_BACKEND_ERRORS';